### PR TITLE
Add connect wallet

### PR DESCRIPTION
**Pull request by clairecharles**
Fixes issue: 
Add web3 wallet integration #4

Description: I added a wallet integration for metamask

### CODE REVIEW

**Comment by iemwill** [comment]
First of all thanks for your work. There are some changes necessary to be merged.

1. I will create a branch called develop-web3wallet, please make a pr to that branch.
2. Since you work with yarn add `yarn-error.log` and `yarn.lock` to the `.gitignore` file.
3. Please change all " to ' so that its consistent through all files to use '.

And one question, how was the installation process? I had some problems recently and it was necessary to use --force.

**Review by iemwill — CHANGES_REQUESTED** [review]
As in the comment https://github.com/iemwill/hellow/pull/26#issuecomment-1300923073

**Comment by clairecharles** [comment]
> First of all thanks for your work. There are some changes necessary to be merged.
> 
> 1. I will create a branch called develop-web3wallet, please make a pr to that branch.
> 2. Since you work with yarn add `yarn-error.log` and `yarn.lock` to the `.gitignore` file.
> 3. Please change all " to ' so that its consistent through all files to use '.
> 
> And one question, how was the installation process? I had some problems recently and it was necessary to use --force.

sure I will make the necessary changes I used yarn install for the installation process

**Comment by iemwill** [comment]
Done by [27abe91](https://github.com/iemwill/hellow/commit/27abe9136a1fc60d52a76004180e22e23183a929)

**Pull request closed without merging**
